name: Patch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: prepare
        run: |
          ${{ secrets.PREPARE_CLI }}

      - name: Build youtube
        run: |
          export patch_args="--exclusive \
            -i custom-video-buffer \
            -i disable-auto-captions \
            -i disable-startup-shorts-player \
            -i general-ads \
            -i hdr-auto-brightness \
            -i hide-create-button \
            -i hide-endscreen-cards \
            -i hide-info-cards \
            -i hide-my-mix \
            -i hide-shorts-button \
            -i hide-watch-in-vr \
            -i hide-watermark \
            -i microg-support \
            -i minimized-playback \
            -i open-links-directly \
            -i premium-heading \
            -i remember-video-quality \
            -i seekbar-tapping \
            -i sponsorblock \
            -i video-ads"
          bash patch.sh

      - name: Upload Build Artifact(youtube)
        uses: actions/upload-artifact@v3
        with:
          name: revanced-youtube
          retention-days: 1
          path: |
            revanced-youtube*.apk

      - name: Build tiktok
        run: |
          export patch_args="--exclusive \
            -i settings \
            -i feed-filter \
            -i hide-ads \
            -i playback-speed \
            -i show-seekbar"
          export patch_target=tiktok
          bash patch.sh

      - name: Upload Build Artifact(tiktok)
        uses: actions/upload-artifact@v3
        with:
          name: revanced-tiktok
          retention-days: 1
          path: |
            revanced-tiktok*.apk
